apiVersion: v1
kind: Service
metadata:
  name: redis-master-external
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - name: redis-tls
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master
---

