---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-proxy
  namespace: redis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - redis-api.alexbartleynees.com
      secretName: redis-proxy-tls
  rules:
    - host: redis-api.alexbartleynees.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-proxy
                port:
                  number: 3000
