ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  timeout:
    connect: "5"
    read: "60"
    send: "60"
  hosts:
    - domain: alexbartleynees.com
    - domain: www.alexbartleynees.com

  namespace: portfolio-site

  services:
    - name: portfolio-site
      path: /
      pathType: Prefix
      serviceName: portfolio-site-svc
      servicePort: 4321

tls:
  enabled: true
  secretName: portfolio-tls
