ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  maxBodySize: "8m"
  timeout:
    connect: "5"
    read: "60"
    send: "60"

  hosts:
    - domain: api-product-feedback.alexbartleynees.com

  namespace: product-feedback

  services:
    - name: product-feedback-api
      path: /api
      pathType: Prefix
      serviceName: product-feedback-api-svc
      servicePort: 5185

tls:
  enabled: true
  secretName: product-feedback-api-tls
