ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  maxBodySize: "8m"
  timeout:
    connect: "5"
    read: "60"
    send: "60"

  hosts:
    - domain: product-feedback.alexbartleynees.com

  namespace: product-feedback

  services:
    - name: product-feedback-app
      path: /
      pathType: Prefix
      serviceName: product-feedback-app-svc
      servicePort: 4000

tls:
  enabled: true
  secretName: product-feedback-app-tls