resources:
  - apps
  - jellyfin
  - jellyseer
  # MetalLB and cert-manager Applications are in infrastructure app
  - metallb/ipaddresspool.yaml
  - ingress/nginx-ingress.yaml
  # cert-manager Application is in infrastructure app
  - certs/cluster-issuer.yaml
  - database/database.yaml
  - database/backup.yaml
  - redis
  - redis-proxy
  - secrets
  - storage/application.yaml
  - metrics
