resources:
  - apps
  - jellyfin
  - jellyseer
  - metallb/metallb.yaml
  - metallb/ipaddresspool.yaml
  - ingress/nginx-ingress.yaml
  - certs/cert-manager.yaml
  - certs/cluster-issuer.yaml
  - database/database.yaml
  - database/backup.yaml
  - redis
  - redis-proxy
  - secrets
  - storage/application.yaml
  - metrics
