resources:
  # Portfolio applications
  - portfolio-site.yaml
  - product-feedback-api.yaml
  - product-feedback-app.yaml
  - product-feedback-bff.yaml

  - dopamine-kick-bff.yaml
  - dopamine-kick-app.yaml
  - dopamine-kick-api.yaml

  # Database and cache
  - database.yaml
  - backup-app.yaml

  # Identity and authentication
  - keycloak-app.yaml

  # Media services
  - immich-photos.yaml
  - jellyfin-app.yaml
  - jellyseer-app.yaml

  # Productivity
  - obsidian-livesync.yaml

  # Redis
  - redis.yaml
  - workloads/redis
  - redis-proxy-app.yaml

  # Storage
  - seaweedfs.yaml
  - workloads/seaweedfs

  # Otel
  - workloads/observability-workloads

  # RabbitMQ
  - rabbitmq.yaml
